### ISSUE TITLE
Unable to highlight chart / navigator with streaming data

### ISSUE THREAD

**Issue by udyandutta** [PredixDev/px-vis-timeseries#10]
Hey, 
We're unable to select chart data with continuously streaming timeseries data. The selected portion of the char resets the moment there is new incoming data. Also unable to select chart data on the navigator.

Issue seen on "version": "0.2.1".

Adding a small gif to help explain the issue.

![issue2](https://cloud.githubusercontent.com/assets/18316512/18220905/9892c35a-712b-11e6-898c-8ccabc17eb6d.gif)

**Comment by jay3dec** [comment]
@udyandutta any updates on this issue ??

**Comment by udyandutta** [comment]
No updates so far @jay3dec. Not working on this component for now. Free free to close if not reproducible.

**Comment by nonmetalhail** [comment]
This is an issue that will be fixed in the v1.0 version that will be released this coming month. 

What do you mean events disappear? @jay3dec

**Comment by udyandutta** [comment]
@nonmetalhail can we expect the fix to be out soon ?

**Comment by nonmetalhail** [comment]
Included in the v1.0 release. Use the `disableDynamicUpdate` boolean property to disable it.
