### ISSUE TITLE
Readme.md refers to grunt but gulp is used.

### ISSUE THREAD

**Issue by reyotch** [PredixDev/px-vis-timeseries#17]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Expected behavior and actual behavior:
Readme.md describes how to compile and run demo.

## Steps to reproduce the problem:
git clone :)

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
N/A

**Comment by mdwragg** [comment]
Fixed
