### ISSUE TITLE
Resizing the browser window while the chart is zoomed causes a reset of chart timeline.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-vis-timeseries#20]
1. Zoom on a time series chart.
2. Resize the browser window while the chart is zoomed.
3. Note the chart is resized back to the initial timeline and the reset zoom button hangs outside of the chart.

Tags: Timeseries 0.5.2 + Vis 0.6.35
See Screenshot below:

![resize_zoomedchart](https://cloud.githubusercontent.com/assets/10835611/20402116/51a7b52a-acb0-11e6-8296-6033710794c1.png)

**Comment by benoitjchevalier** [comment]
fixed in next major version

**Comment by benoitjchevalier** [comment]
Actually now fixed in v0.5.8 (vis 0.7.3)
