### ISSUE TITLE
Margin and margin-nav don't work in time series...

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-vis-timeseries#21]
We should look into margin and margin-nav. They seem to be ineffective when used in time series tag, e.g.
margin='{
            "top": 250,
            "right": 50,
            "bottom": 200,
            "left": 10
          }'
This is with vis 0.6.35 and TS 0.5.2.

**Comment by nonmetalhail** [comment]
My bad; they are not dev settable at this time.
