### ISSUE TITLE
investigate margin and margin-nav

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-vis-timeseries#22]
We should look into margin and margin-nav. They seem to be ineffective when used in time series, e.g.
margin='{
            "top": 250,
            "right": 50,
            "bottom": 200,
            "left": 10
          }'
This is with vis 0.6.35 and TS 0.5.2.

**Comment by nonmetalhail** [comment]
Yes; they are not supposed to be overwritten. Private to chart.
