### ISSUE TITLE
vis-thresholds not applying to graph correctly

### ISSUE THREAD

**Issue by pbelch** [PredixDev/px-vis-timeseries#25]
Hi.

I am trying to add a threshold line to a timeseries graph, and although it is appearing, it is appearing in the wrong place and with d3 library errors.

Code below, and screenshots attached

`<px-vis-timeseries height="300" width="800" prevent-resize="true" selection-type="xy" enable-tooltip="true" register-location="top" chart-data='[
        {"x":1397177400000,"upper":"2","lower":"1","value":"1.5"},
        {"x":1397228040000,"upper":"2","lower":"1","value":"2.14"},
        {"x":1397248260000,"upper":"2","lower":"1","value":"1.89"},
        {"x":1397291280000,"upper":"3","lower":"2","value":"2.895"},
        {"x":1397318100000,"upper":"3","lower":"2","value":"2.21"},
        {"x":1397342100000,"upper":"4","lower":"3","value":"3.5"}
        ]' include-all-series="true"
        event-data='[{"id":"ThresChange","label":"ThresChange","x":"1397291280000"}]'
        event-config='{"ThresChange":{"color":"blue","icon":"fa-camera","type":"fa","offset":[0,0]}}'
        time-data="Date"
        x-axis-config='{"title":"Created Date","labelPosition":"center","orientation":"bottom"}' y-axis-config='{"title":"Recoded Value","labelPosition":"center","orientation":"left"}'
        ></px-vis-timeseries>
`
![thresherror](https://cloud.githubusercontent.com/assets/9989676/20833697/e467ff9e-b888-11e6-815b-b3fb6e94d883.png)

**Comment by nonmetalhail** [comment]
All your numbers are cast as strings. Please remove the quotes. That undoubtable is why the timestamp is wrong. 

Also FYI, you're using Events, not Thresholds. That is a separate component.

**Comment by benoitjchevalier** [comment]
closing for now
