### ISSUE TITLE
X-axis: timezone shift applied (but not on tooltip of the same graph)

### ISSUE THREAD

**Issue by arnaudLC35** [PredixDev/px-vis-timeseries#26]
Hi,

## Expected behavior and actual behavior:
When displaying data (in UTC) with timeseries and requesting the data to be displaying in UTC (default behavior in documentation) the time in the tooltip is correctly displayed (in UTC), however the time zone shift is applied to the X-axis. example in the following screenshot:

![timeserietimezone](https://cloud.githubusercontent.com/assets/15925080/20880944/1487c15a-baeb-11e6-9dea-7624ad5e0e40.png)

## Environment:
Chrome: Version 54.0.2840.99 m
px-vis v0.7.5 and px-vis-timerseries v0.5.8 master branches

Thanks,

Arnaud

**Comment by nonmetalhail** [comment]
This will be resolved in v1.x and the axis will standardize on UTC by default. In the meantime, to bring the two into sync you can,

1) change the tooltip or register timezone. You'll have to do this via a configuration object.

```
<px-vis-timeseries
    tooltip-config='{
        "timezone": "America/Los_Angeles”
    }'
</px-vis-timeseries>
```
 
2) change the axis to utc

```
<px-vis-timeseries
    x-axis-config="[[_getXAxisConfig()]]"
</px-vis-timeseries>
 
_getXAxisConfig : function() {
    return {
        “tickFormat”: Px.d3.utcFormat('%H:%M:%S')
    };
}
```

**Comment by arnaudLC35** [comment]
Thanks for the fix! work perfectly.
