### ISSUE TITLE
First and second date time formats are not applied

### ISSUE THREAD

**Issue by manderson23** [PredixDev/px-vis-timeseries#27]
Setting `first-date-time-format="HH:mm:ss"` and `second-date-time-format="YYYY"` on `px-vis-timeseries` does not override the defaults as expected from reading the documented properties.

**Comment by nonmetalhail** [comment]
Yes, this bit is confusing. Instead of applying these to the chart itself, you'll want to apply these from within a tooltipConfig or registerConfig object depending on which you are using

```
<px-vis-timeseries
    register-config='{
        firstDateTimeFormat: "HH"
    }'>
```

**Comment by manderson23** [comment]
Thanks.
