### ISSUE TITLE
Support min/max y values with shading between the values

### ISSUE THREAD

**Issue by manderson23** [PredixDev/px-vis-timeseries#28]
Support a series with both min and max Y values plus support for shading between the min/max lines.

Something like the following screenshot.
![screenshot from 2016-12-05 15-39-40](https://cloud.githubusercontent.com/assets/1684641/20891190/9af18a9e-bb01-11e6-9f7b-56b41a343300.png)

**Comment by nonmetalhail** [comment]
What do you mean by "both min and max"?

**Comment by manderson23** [comment]
A single Y series with multiple values e.g.
```
x: 12345
yMin: -5
yMax: 5
```
Where the upper line drawn by `yMax` the lower line by `yMin` and in between is shaded.

**Comment by nonmetalhail** [comment]
Ok, you can currently do that via the defaultSeriesConfig object. You'll want to change yMin to dynamic.

Note that this behavior will be simplified in v1.x via chartExtents.

For the area component, please go to Aha and log a request so out PM can prioritize that request

**Comment by manderson23** [comment]
Aha?

**Comment by benoitjchevalier** [comment]
Aha is our internal tool within GE to submit feature requests that can then be prioritized. If you are not internal to GE you can submit an enhancement request via a separate github issue (in this case probably on the px-vis repo). We'll then take this request in our internal tool

**Comment by manderson23** [comment]
I've been able to create the min/max chart I want without the shading.

I'll see if I can submit a feature request via Aha.

**Comment by nonmetalhail** [comment]
If you are unable to access Aha, let us know and we can add your request. Just better if you do so you can track it and get updates  ;)
