### ISSUE TITLE
Multi-Y axis support

### ISSUE THREAD

**Issue by nonmetalhail** [PredixDev/px-vis-timeseries#3]

**Comment by davidsteinberger** [comment]
Hi, I'm currently evaluating the px-vis framework for us. It's promising, but that's a deal breaker right now. Is there any ETA on this? I wouldn't mind helping land this feature, but would need some help to get started.

**Comment by nonmetalhail** [comment]
Hi David,

Multi-axis support for timeseries is scheduled for delivery in Q1 2017. It is a priority enhancement and I would hope to release it before the end of this year. Failing that, early Q1.

**Comment by benoitjchevalier** [comment]
Fixed with 1.0.0 release
