### ISSUE TITLE
Override format used for X axis labels on navigator

### ISSUE THREAD

**Issue by manderson23** [PredixDev/px-vis-timeseries#30]
By default 12 hour format seems to be used for the hours on both the X axis of the chart and navigator.

I'd like to use 24 hour format to match how I have configured the register first time format.

Perhaps this is already available but I can't see anything obvious in the docs or code.

**Comment by benoitjchevalier** [comment]
Hello,

you can use the "tickFormat" property on "xAxisConfig". This property uses the [d3 time format](https://github.com/d3/d3-time-format) or [d3 format](https://github.com/d3/d3-format) and is very flexible.

**Comment by nonmetalhail** [comment]
To follow up, unfortunately, the navigator is not currently configurable. Another pending change for v1.x

**Comment by manderson23** [comment]
I notice that when the default tick format is used for the x axis as you zoom in the tick labels change as appropriate to the zoom level.

However, when I set the format myself that format is used no matter the zoom level.

Is it possible to set your own format but also maintain the behaviour of changing the labels as you zoom?

**Comment by nonmetalhail** [comment]
Unfortunately, not that I know of; that is native d3 functionality and I do not know of an easy way to do this. You can try searching on d3 forums and let me know if you do find a way.

The hard way is you would have to do it manually, passing in different formats at different zoom levels.

**Comment by manderson23** [comment]
Using the example for a multi-scale time format [here](https://github.com/d3/d3-time-format) I was able to configure the x axis formatting and maintain the behaviour on zoom.

     var formatMillisecond = Px.d3.timeFormat(".%L"),
        formatSecond = Px.d3.timeFormat(":%S"),
        formatMinute = Px.d3.timeFormat("%H:%M"),
        formatHour = Px.d3.timeFormat("%H"),
        formatDay = Px.d3.timeFormat("%a %d"),
        formatWeek = Px.d3.timeFormat("%b %d"),
        formatMonth = Px.d3.timeFormat("%B"),
        formatYear = Px.d3.timeFormat("%Y");

     function multiFormat(date) {
         return (Px.d3.timeSecond(date) < date ? formatMillisecond
              : Px.d3.timeMinute(date) < date ? formatSecond
              : Px.d3.timeHour(date) < date ? formatMinute
              : Px.d3.timeDay(date) < date ? formatHour
              : Px.d3.timeMonth(date) < date ? (Px.d3.timeWeek(date) < date ? formatDay : formatWeek)
              : Px.d3.timeYear(date) < date ? formatMonth
              : formatYear)(date);
      }
      var config = {};
      config.tickFormat = multiFormat;
      return config;`

I'll update the issue description to reference overriding the x axis configuration for the navigator.

**Comment by benoitjchevalier** [comment]
the navigator x axis config can now be changed in `navigatorConfig` in 1.0.0
