### ISSUE TITLE
Support disabling zoom

### ISSUE THREAD

**Issue by manderson23** [PredixDev/px-vis-timeseries#31]
I have a chart showing live data. When you zoom in the chart resets on the next update.

I'd prefer to be able to disable zooming completely for charts showing live data. It doesn't appear that this is possible from the existing API.

**Comment by nonmetalhail** [comment]
Live data as in streaming data in?

You are correct. There is at present no way to disable zooming and the chart resets extents on new data load. There will be a way to disable the extent update in v1.x

**Comment by manderson23** [comment]
Live data is streaming in. In this exact case I'm adding a new point and removing the oldest point to keep the chart a fixed length.

**Comment by nonmetalhail** [comment]
Included in the v1.0  release. Use the disableDynamicUpdate boolean property to disable it.

**Comment by nonmetalhail** [comment]
Oops, sorry, I lied; that property is to stop the navigator from updating to the full data extents. It does not disable all zooming

**Comment by benoitjchevalier** [comment]
You can now disable zooming on the chart by specifying `null` for the mouseDown/mouseUp event listeners in actionConfig:

```
             {
                'mousedown': 'null',
                'mouseup': 'null'
              }
```
