### ISSUE TITLE
PX color

### ISSUE THREAD

**Issue by sravananantula** [PredixDev/px-vis-timeseries#33]
# Submit an Issue

Hi,

## Expected behavior and actual behavior:
We have 1 card with multiple charts , each chart have tags with different color. When we are setting custom color to each tag, series is not picking up the color.It always taking default color series order.

## Steps to reproduce the problem:
Unable to set the custom color to px-vis-timeseries chart

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
Using px-vis-timeseries version#0.4.1

## Code examples help us better understand the issue - follow the appropriate codepen for the 

<px-vis-timeseries 
         id="{{chart.id}}"
           options='{
          "enableTooltip":true,
         "selectionType": "xy",
         "registerLocation":"none",
         "yAxisConfig": {
            "preventSeriesBar":true
           }}'
          include-all-series
         render-to-canvas
          selection-type= "xy"
          chart-data="[[chartData]]"
       disable-navigator="{{isDetail}}"
          >
        </px-vis-timeseries>
    <px-vis-data-converter
    id="dataConverter" 
    data-key = "data"
    id-key = "id"
    name-key="name"
    original-data = "[[actualData]]" 
    series-config="{{seriesConfig}}"
    chart-data="{{chartData}}">   
  </px-vis-data-converter>

Script for series config:
 addSeriesConfig: function(seriesArray) {
              var self =this;
              self.seriesConfigObjs=[];
              seriesArray.forEach(function(series){
                  //if series does not exist in seriesConfigObjs , then add it.
               //  if (self.seriesConfigObjs[series.taginfo.sourceKey] === undefined) {
                      self.seriesConfigObjs[series.taginfo] = {
                    	 y: series.taginfo,
                          x: 'x',
                         // yAxisUnit: series.taginfo.details.unit,
                          name: series.taginfo,
                          color: series.color,
                          mutedOpacity: 0
                      };
                      
                    
                  //}
              });

**Comment by benoitjchevalier** [comment]
Hello,

what is the format of your color? It should be passed in as a string `rgb(xxx,xxx,xxx)`. The feature works as seen on this [codepen](http://codepen.io/FrenchBen/pen/GNzBrN?editors=1111).

You might also want to make sure to you use the Polymer 'set' API on your chart when changing the series config. If changing a property of the series-config you might have to unset/reset the series-config for Polymer to bypass its dirty check on process your change, i.e:

```
//do your code to generate/change the series config

//reset the config so we bypass dirty check
theChart.set('seriesConfig', {});

theChart.set('seriesConfig', yourNewConfigObject);
```

Please note that resetting the config to an empty object won't be needed anymore when Polymer 2.0 comes in.

**Comment by sravananantula** [comment]
Hi,
Thank you for the answer.
 Passing color is working fine now from my code. Issue was i was using like this 
<px-vis-timeseries  series-config="[[seriesConfig]]"> <px-vis-data-converter  series-config="{{seriesConfig}}" >
instead i am having series-config only for px-vis-timeseries did not add it for px-vis-data-converter 
like below
<px-vis-timeseries  series-config="{{seriesConfig}}">
