### ISSUE TITLE
Graph is plotted in UTC time; enable flag for timeLocal

### ISSUE THREAD

**Issue by ericcquachh** [PredixDev/px-vis-timeseries#34]
## Expected behavior and actual behavior:
Expected Behavior: Graph, Tooltip, and Register Config should be plotted in browser local time. 
Actual Behavior: Graph, Tooltip, and Register Config is plotted in UTC time.

**Comment by benoitjchevalier** [comment]
More exactly we need to expose the flag for configuration but the default is still going to be UTC. Functionality is there, we just need to expose it

**Comment by ericcquachh** [comment]
Sounds good @benoitjchevalier

**Comment by nonmetalhail** [comment]
Will be included in the v1.0.0 release

**Comment by benoitjchevalier** [comment]
Fixed with 1.0.0 release
