### ISSUE TITLE
truncationLength not working

### ISSUE THREAD

**Issue by sjw787** [PredixDev/px-vis-timeseries#37]
We are trying to use the property truncationLength as specified in the documentation at - https://www.predix-ui.com/#/components/px-vis-timeseries/ 

[
<img width="1096" alt="screen shot 2017-02-07 at 1 12 28 pm" src="https://cloud.githubusercontent.com/assets/6579537/22704914/701fd196-ed37-11e6-9730-e0d732f977b7.png">
](url)

It seems that this property does not work or is not supported yet.

### Here is where we are trying to use it in our application:

<img width="656" alt="screen shot 2017-02-07 at 1 13 21 pm" src="https://cloud.githubusercontent.com/assets/6579537/22704915/703e0ca6-ed37-11e6-9609-02ca960af62b.png">

### Here is the tag for our px-vis-timeseries:

`                  <px-vis-timeseries
                    id="SchTrendChart"
                    include-all-series="true"
                    enable-tooltip="true"
                    prevent-resize="true"
                    width="900"
                    height="400"
                    truncation-length="-1"
                    selection-type="xy"
                    register-location="top"
                    chart-data='[{"x":0,"CANCELLATION":0,"RESCHEDULE IN":0,"RESCHEDULE OUT":0,"OVERDUE":0},
                                 {"x":0,"CANCELLATION":0,"RESCHEDULE IN":0,"RESCHEDULE OUT":0,"OVERDUE":0},
                                 {"x":0,"CANCELLATION":0,"RESCHEDULE IN":0,"RESCHEDULE OUT":0,"OVERDUE":0},
                                 {"x":0,"CANCELLATION":0,"RESCHEDULE IN":0,"RESCHEDULE OUT":0,"OVERDUE":0},
                                 {"x":0,"CANCELLATION":0,"RESCHEDULE IN":0,"RESCHEDULE OUT":0,"OVERDUE":0},
                                 {"x":0,"CANCELLATION":0,"RESCHEDULE IN":0,"RESCHEDULE OUT":0,"OVERDUE":0},
                                 {"x":0,"CANCELLATION":0,"RESCHEDULE IN":0,"RESCHEDULE OUT":0,"OVERDUE":0}]'>
                  </px-vis-timeseries>`

**Comment by benoitjchevalier** [comment]
Hello,

you need to pass the truncationLength to the appropriate config object, ie registerConfig and/or tooltipConfig

`register-config='{ "truncationLength": 500}'`

Let me know if you have more issues with it.

Cheers,
Ben
