### ISSUE TITLE
Property to disable vertical lines in event markers

### ISSUE THREAD

**Issue by GearsAD** [PredixDev/px-vis-timeseries#39]
# Submit an Issue

Hi,

Would it be possible to include a property to disable the vertical lines with event markers? We are seeing part of our graph being occluded because of the lines.

## Expected behavior and actual behavior:
At the moment event markers are always accompanied with a black vertical line. If there are many event markers, it becomes difficult to see the graph.

## Steps to reproduce the problem:
Include any event markers and note the strong vertical black lines, as in the screenshot below.

## Environment:
px-vis-timeseries: v1.0.0-beta3
Chrome: 56.0.2924.87

## Screenshots:
![markers](https://cloud.githubusercontent.com/assets/6854507/23476010/e24a0a36-fe7e-11e6-839e-a9f6ef8ee47e.png)

Thanks,
Sam

**Comment by nonmetalhail** [comment]
That ability should be present in v1.0.0-beta3.

In your eventConfig, you'll want to add either a `lineColor` or `lineWeight` property. Setting either `lineColor` to `null` or `lineWeight` to `0` should work.

Example:

```
eventConfig = {
      "Event Name 1":{
        "color": "blue",
        "icon": "fa-camera",
        "type": "fa",
        "offset":[0,0],
        "lineWeight": 0
      }
}
```

**Comment by GearsAD** [comment]
Works like a charm - thank you!

- Sam

**Comment by nonmetalhail** [comment]
Great, glad to hear it; there is always that fear with a beta that maybe it doesnt really work :)

One word of warning, I've noticed different icons can have slightly different origin points. The line helps you notice when the icon is not really centered. So when trying a new icon, it is probably best to test it out with the line and note how much offset you'll need to align the marker.
