### ISSUE TITLE
Interpolation by series

### ISSUE THREAD

**Issue by davidsteinberger** [PredixDev/px-vis-timeseries#40]
This is not bug, rather a feature request (is there a template for that?). 

I'd be great if we could define different interpolation functions via the `series-config`.
Currently `<px-vis-timeseries>` allows to set 1 _interpolation-function_ at the chart level which is then passed down to the individual `<px-vis-line-*>` components, but it does not allow to set different interpolation functions for different series.

I am aware that Polymer does not allow to pass functions via a data-binding. One workaround would be, to pass a key which is then used to lookup an interpolation function. I'd be happy to discuss this further and could also send a PR for `<px-vis>` if that feature gets accepted.

**Comment by nonmetalhail** [comment]
Adding in v1.1. 

I've added the ability for interpolation curves to be passed in the seriesConfig and the lookup by key. 

The reason I didnt do a lookup originally is that many of the functions require additional parameters. So I've added that ability in, but only for the "simple" functions that do not require any parameters:
```
"curveBasis"
"curveBasisClosed"
"curveBasisOpen"
"curveLinear"
"curveLinearClosed"
"curveMonotoneX"
"curveMonotoneY"
"curveNatural"
"curveStep"
"curveStepAfter"
"curveStepBefore"
```

If you want to use other interpolators, you'll still have to pass them in as functions. 

It is true that you cannot directly bind a function, which is annoying, but the workaround is:

```
<px-vis-timeseries
    ...
    interpolation-function="[[ _returnInterpolator() ]]">
</px-vis-timeseries>

<script>
    _returnInterpolator: function() {
        return Px.d3.curveBasis;
    }
</script>
```

Now that you can pass in a per series interpretor, your seriesConfig now can look like:
```
{
    "mySeries2":{
        "type":"line",
        "name":"mySeries2",
        "x":"x",
        "y":"y2",
        "color": "rgb(250,164,58)",
        "interpolationFunction": Px.d3.curveBasis
    }
}
```
or

```
{
    "mySeries2":{
        "type":"line",
        "name":"mySeries2",
        "x":"x",
        "y":"y2",
        "color": "rgb(250,164,58)",
        "interpolationFunction": "curveBasis"
    }
}
```

**Comment by davidsteinberger** [comment]
That's great news! Thanks!
