### ISSUE TITLE
px-vis-timeseries y-axis bug

### ISSUE THREAD

**Issue by dwarhya** [PredixDev/px-vis-timeseries#41]
Hi,

I am having problems getting the px-vis-timeseries to redraw itself when I dynamically add new series, if the new series is currently out of the range of the currently drawn Y axis

I have created a fiddle (https://jsfiddle.net/dwarhya/652vfv5g/14/) to demonstrate the problem. If you run the fiddle as-is, you will see y0 added and displayed. 1 second later, y1 is added to the chart but the chart does not draw the data points. If you uncomment the last block of code and re-run the fiddle, it will then render y0, y1 and y2 properly

I am using px-vis-timeseries 0.6.7

Lee

**Comment by nonmetalhail** [comment]
Hi,

The fiddle appears to be working for us (though not behind GE proxies for some reason; a codepen copy of your code also works fine behind proxies). One reason for this difference might be that the fiddle/codepen pulls the latest version of the px components. v1.0 of timeseries was released on Friday. 

One issue that may explain why it is not working for you is that you are not using the Polymer set and push methods which may cause the data observers not to fire. This is a common problem with Polymer components. Please see https://www.polymer-project.org/1.0/docs/api/Polymer.Base#method-set

Also, width="auto" is not valid. It must be a number, but it is also doesnt have to be specified if you want it dynamic.

**Comment by dwarhya** [comment]
Hi,

Fixed with v1.0.0. Thank-you
