### ISSUE TITLE
px-vis-timeseries negative numbers bug

### ISSUE THREAD

**Issue by dwarhya** [PredixDev/px-vis-timeseries#42]
I have found an issue when dynamically adding series with negative values. This may or may not be related to this bug (https://github.com/PredixDev/px-vis-timeseries/issues/41)

I have created a fiddle (https://jsfiddle.net/dwarhya/652vfv5g/15/) to clearly show the problem -> y2 goes off-screen

I am using px-vis-timeseries 0.6.7

Lee

**Comment by nonmetalhail** [comment]
Hi,

You need to specify that you want your extents to be "dynamic" for this to work. For a v1.0 configuration, please see: http://codepen.io/nonmetalhail/pen/YZQeKz?editors=1011

**Comment by dwarhya** [comment]
Hi

Fixed with v1.0.0. Thank-you
