### ISSUE TITLE
Multiplying the value of dynamic chartExtents

### ISSUE THREAD

**Issue by hackily** [PredixDev/px-vis-timeseries#46]
I currently have the chartExtents set up to be dynamic.
```
          chart-extents='{
            "x": ["dynamic", "dynamic"],
            "y": ["dynamic", "dynamic"]
          }'
```
Is there a way to make the default chartExtents the max and min values * 1.1 or something?
As seen in this pic, the charted line is literally at the top of the graph because the numbers vary so little.
![](http://i.imgur.com/h6HyCqt.png)

**Comment by nonmetalhail** [comment]
No, there is no way to currently do this other than manually passing in the calculated value into chartExtents.
