### ISSUE TITLE
Allow to set timezone for events

### ISSUE THREAD

**Issue by davidsteinberger** [PredixDev/px-vis-timeseries#47]
## Expected behavior and actual behavior:

I'm not sure if this should be considered a feature request or a bug. But IMO it should be possible to set the timezone for the events. `<px-vis-event>` exposes a timezone property for this, but <px-vis-timeseries> does not expose it to the dev.

## Steps to reproduce the problem:

Use any version of `<px-vis-timeseries>` and add some event.
The event is going to be interpreted in UTC and displayed w/ _+0000_ offset even if the x-axis and tooltips have a timezone offset of e.g. _+0200_.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

NA

**Comment by nonmetalhail** [comment]
Guess I'm late responding to this, but this was added with vis v1.1.11.

* added more config to `eventsConfig`:
      - `firstDateTimeFormat`: moment.js format string for the first part of the timestamp if the x Axis is time based
      - `separator`: the separator character between the two datetime strings
      - `secondDateTimeFormat`: moment.js format string for the second part of the timestamp if the x Axis is time based
      - `tooltipOrientation`: orientation of the tooltip
      - `timezone`: the moment.js timezone to be used for the timestamp
