### ISSUE TITLE
y-axis-config property not taking dynamically updated JSON objects

### ISSUE THREAD

**Issue by wjgarcia2016** [PredixDev/px-vis-timeseries#48]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Expected behavior and actual behavior:
Expecting the y-axis-config property to display title and unit data alongside the y-axis, but when passing a JSON object to y-axis-config it results in nothing being displayed for the title or unit.
This problem only exists for the y-axis-config.  The x-axis-config works when passing in a JSON object.
## Steps to reproduce the problem:
Pass a valid JSON object into y-axis-config.
## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
Browser: Google Chrome Version 57.0.2987.133
OS: Windows 7 Pro
## Screenshots (_optional, but very helpful_):
![image](https://cloud.githubusercontent.com/assets/23720803/24775749/15bc1a56-1aec-11e7-9077-73ba43eb3757.png)

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
![image](https://cloud.githubusercontent.com/assets/23720803/24775924/d109332a-1aec-11e7-8ad7-d4ba887491c8.png)

**Comment by nonmetalhail** [comment]
what JSON object are you passing in? Your syntax for the x and y axis configs looks off. What are you trying to do with it?

**Comment by wjgarcia2016** [comment]
I am trying to use the Polymer app-localize-behavior package to read in a translated word from a JSON file.  The problem is it works for the x-axis-config, but doesn't work for the y-axis-config.  The data binding to the localize("TIME") function returns the translated word.

**Comment by nonmetalhail** [comment]
The listener for the y axis config is elsewhere. 

I don't know why this would work because I still think you have a syntax error because you have double quotes around the binding and around your string inside the binding. 

Can you try either putting `"TIME"` inside a property and calling that:

```
y-axis-config='{"title": "{{localize(myStr)}}"}'
```

Or possibly better, build the whole obj in javascript and pass it in:
```
y-axis-config='[[_returnObj()]]'

...
_returnObj: function() {
    var title = localize("TIME");
    return {"title": title};
}
```
Otherwise, I think you'll have to create a codepen demonstrating the issue.

**Comment by wjgarcia2016** [comment]
I am going to refer to this issue with using the localize function in pure JavaScript: https://github.com/PolymerElements/app-localize-behavior/issues/57

**Comment by nonmetalhail** [comment]
And did you try computed values as suggested in that issue?

**Comment by wjgarcia2016** [comment]
It took a couple tries but giving the property a computed function and handling it that way eventually worked, thanks for that suggestion.

**Comment by nonmetalhail** [comment]
Sweet. Glad to hear it since we havent dealt with the localize stuff yet.
