### ISSUE TITLE
vvrhclkdgbvvguvjbddlikggvitkgchkbnlhclddgbur

### ISSUE THREAD

**Issue by or9** [PredixDev/px-vis-timeseries#49]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by benoitjchevalier** [comment]
waEROIUrwqopiurwqPIOUDQWpou'dqwpiodwp[odwop['dwap[odwqP[ODQWop[dQWP[OKDQWA;podaqP;'LAsdda

**Comment by mdwragg** [comment]
💯
