### ISSUE TITLE
redraw issue after chart data changed

### ISSUE THREAD

**Issue by soccerchenjun** [PredixDev/px-vis-timeseries#50]
Hi,

I have created an element like
<px-vis-timeseries
        id="tschart"
		width="800"
        height="300"
        prevent-resize="true"
        enable-tooltip="true"
        register-location="none"       
		x-axis-type="timeLocal"		
        register-config='{"timezone":"Asia/Shanghai"}' 
        y-axis-config="{{yaxisCfg}}"
        margin='{"top":30,"bottom":60,"left":85,"right":65}' 		
        series-config="{{seriesCfg}}"
        selection-type= "xy"		
        chart-data="{{tsChartData}}">
      </px-vis-timeseries>

first time ,  the chart can be rendered after data is fetched by iron-ajax
after I have updated chart data with empty array [{x:0,y:0}] and series config, the chart and navigator can't be redrawn. previous graph still exists.
my initial series config is 
{"val": { "type":"line", "x": "x", "y": "y", "yAxisUnit": "" ,"axis":{"id":"axis1","side":"left","number":"1"}}}
when I have changed chartdata, series config has only changed series key

**Comment by nonmetalhail** [comment]
What version?

How are you updating the properties? Are you using the polymer methods?

Can you recreate in a codepen?

**Comment by soccerchenjun** [comment]
version 1.1.1
`<px-vis-timeseries
        id="tschart"
		width="800"
        height="300"
		debounce-resize-timing="250"
		progressive-rendering-points-per-frame="16000" 
		progressive-rendering-min-frames="1" 
        prevent-resize="true"
        enable-tooltip="true"
        register-location="none"       
		x-axis-type="timeLocal"		
		chart-extents='{"x":["dynamic","dynamic"],"y":["dynamic","dynamic"]}'
        register-config='{"timezone":"Asia/Shanghai"}' 
        y-axis-config="{{yaxisCfg}}"
        margin='{"top":30,"bottom":60,"left":85,"right":65}' 		
        series-config="{{seriesCfg}}"
        selection-type= "xy"		
        chart-data="{{tsChartData}}">
      </px-vis-timeseries>`
I have updated tsChartData =  [{x:0,y:0}]
not use polymer method, just update binding object, sorry, I have not used codepen before

**Comment by soccerchenjun** [comment]
the screenshot is 
![image](https://cloud.githubusercontent.com/assets/28125566/25521957/0c06b8a0-2c34-11e7-8f7f-0211ed793bdf.png)

**Comment by nonmetalhail** [comment]
OK, you must use the polymer methods to update the properties. If you don't, The binding won't get notified of the change. That's why it isn't redrawing.
Try:
`yourChart.set("chartData", newData)`

**Comment by soccerchenjun** [comment]
when I use set method, an error is raised
winddata-view.html:1041 Uncaught TypeError: chart.set is not a function
    at HTMLElement._formatDataForChart (winddata-view.html:1041)
    at HTMLElement._observerEffect (loader.html:4664)
    at HTMLElement._effectEffects (loader.html:4509)
    at HTMLElement._propertySetter (loader.html:4493)
    at HTMLElement.setter (loader.html:4572)
    at HTMLElement.<anonymous> (loader.html:4615)
    at HTMLElement._notifyListener (loader.html:5132)
    at HTMLElement.<anonymous> (loader.html:4636)
    at HTMLElement.fire (loader.html:4345)
    at HTMLElement._notifyChange (loader.html:4476)

**Comment by nonmetalhail** [comment]
Well, if set is not a function, you must be calling it on the wrong element

**Comment by soccerchenjun** [comment]
chart is pointed at px-vis-timeseries element . could u help me check my file
<link rel="import" href="../../bower_components/polymer/polymer.html">
<link rel="import" href="../../bower_components/px-card/px-card.html">
<link rel="import" href="../../bower_components/iron-ajax/iron-ajax.html">
<link rel="import" href="../../bower_components/px-rangepicker/px-rangepicker.html">
<link rel="import" href="../../bower_components/px-typeahead/px-typeahead.html">



<dom-module id="winddata-view">
  <template>
    <px-card header-text="历史数据">
	    <div class="layout">
	    <div class="layout__item u-1/4">
		    <px-typeahead id="tagQuery" placeholder="Enter Your Search Query" local-candidates="{{tagDescData}}"></px-typeahead>
		</div>
	  <div class="layout__item u-1/2">
	
	   <px-rangepicker
        id="rangepicker"
        range="{{range}}"
        date-format="YYYY/MM/DD"
        time-format="hh:mm:ss A"
        show-buttons="true">
      </px-rangepicker>
	  </div>
	  <div class="layout__item u-1/4">
	  <button class="btn btn--small" id="submitBtn" on-tap="onTap">提交</button>
	  </div>
	  </div>
	  
	 

      <px-vis-timeseries
        id="tschart"
		width="800"
        height="300"
		debounce-resize-timing="250"
		progressive-rendering-points-per-frame="16000" 
		progressive-rendering-min-frames="1" 
        prevent-resize="true"
        enable-tooltip="true"
        register-location="none"       
		x-axis-type="timeLocal"		
		chart-extents='{"x":["dynamic","dynamic"],"y":["dynamic","dynamic"]}'
        register-config='{"timezone":"Asia/Shanghai"}' 
        y-axis-config="{{yaxisCfg}}"
        margin='{"top":30,"bottom":60,"left":85,"right":65}' 		
        series-config="{{seriesCfg}}"
        selection-type= "xy"		
        >
      </px-vis-timeseries>
	 
      
      
	  <iron-ajax url="/histdata/getataghisval?tag=node1cndlvl&begintime=2016-12-12 12:00:00&endtime=2016-12-12 13:00:00" id="tsQueryElement" last-response="{{rawTsData}}" auto></iron-ajax>
      <iron-ajax url="/histdata/getalltagdef" id="thQueryComp" last-response="{{rawThData}}" auto></iron-ajax>
      
      

      
      
    </px-card>

  </template>
  <script>
    Polymer({
      is: 'winddata-view',
      properties: {
        tsChartData: {
          type: Array
        },
		tagDescData: {
          type: Array
        },
		titleData: {
		  type:String,
		  value:''
		},
		unitData: {
		  type:String,
		  value:''
		},
		seriesCfg:{
		  type:Object,
		  value:{"val": { "type":"line", "x": "x", "y": "y", "yAxisUnit": "" ,"axis":{"id":"axis1","side":"left","number":"1"}}}
		},
		yaxisCfg:{
		  type:Object,
		  value:{"title": "val","titleTruncation":false,"axis1":{"title":"val","titleTruncation":false,"unit":""}}
		},
		tagDefData:{
		   type:Array
		},
        rawTsData: {
          type: Object,
          observer: '_formatDataForChart'
        },
		rawThData: {
          type: Object,
          observer: '_formatDataForTypeHead'
        },
        timeseriesQuery: {
          type: Object,
          value: function() {
            return {
              "start": "1y-ago",
              "tags": [
                {
                  "name": "Compressor-2015:CompressionRatio"
                }
              ]
            };
          }
        }
      },
	  ready: function() {
	     
    var rangeTo =  new Date();
    var rangeFrom =  new Date();
	rangeFrom.setDate(rangeFrom.getDate() - 1);
    this._updateRangePicker(rangeFrom, rangeTo);
	
	
	 
	  },
      created: function() {
        this.importHref(this.resolveUrl('../../bower_components/px-vis-timeseries/px-vis-timeseries.html'));
      },
	   onTap: function() {
        
		  var tagname;
		  
		  var strstarttime;
		  var strendtime;
		  
		  var tagunit;
		 
		  for(var i=0; i<this.tagDefData.length; i++)   {
		      if (this.$.tagQuery.value === this.tagDefData[i].desc)
			  {
			     tagname = this.tagDefData[i].name;	
                 tagunit = this.tagDefData[i].unit;				 
				 break;
			  }
		  }
		  
		  
		  
		  var $rangePicker = this.$.rangepicker;
		  strstarttime = moment($rangePicker.range.from).format('YYYY-MM-DD HH:mm:ss');		  
		  strendtime = moment($rangePicker.range.to).format('YYYY-MM-DD HH:mm:ss');
		  
		  
		 // this.$.tschart.canvasContext.clearCanvas();
		  
		  var strcfg;
		  strcfg = '{"'+this.$.tagQuery.value+'":{"type":"line", "x": "x", "y": "y", "yAxisUnit": "'+tagunit+'","axis":{"id":"axis1","side":"left","number":"1"}}}';
		  
		  this.seriesCfg = JSON.parse(strcfg);
		  
		  var stryAxisCfg;
		  stryAxisCfg='{"title":"'+this.$.tagQuery.value+'","titleTruncation":false,"axis1":{"title":"'+this.$.tagQuery.value+'","titleTruncation":false,"unit":"'+tagunit+'"}}';
		  this.yaxisCfg=JSON.parse(stryAxisCfg);
		  //this.$.tschart.chartData = [{x: 0, y: 0}];
		  //this.$.tschart.chartData = [];
		  
		  this.$.tsQueryElement.url = '/histdata/getataghisval?tag='+tagname+'&begintime='+strstarttime+'&endtime='+strendtime;
		 this.tsChartData=[{"x":0,"y":0}];
		 this.tsChartData = [];
		 var chart = document.getElementById('tschart');
		 //this.$.tschart.set("chartData",[{x:0, y:0}]);
		 //this.$.tschart.set('chartData',[]);
		 chart.set('chartData',[{"x":0, "y":0}]);
		  
		 // this.$.tsQueryElement.generateRequest();
		  
		  
      },
	  
	  _formatDataForTypeHead: function(raw) {
	  
	     this.tagDefData = raw.getAllTagInfoResult;
		 
		 var descVals = [];
		 for(var i=0; i<this.tagDefData.length; i++)   {
		   
			
			descVals.push(this.tagDefData[i].desc);
			
		}
		this.tagDescData = descVals;
	  },
      _formatDataForChart: function(raw) {
        var chart = document.getElementById('tschart');
		var series = [];
        var datapoints = raw.getAHisValueResult;
		alert(datapoints.length);
        datapoints.forEach(function(point) {
          series.push({"x": point.time, "y": point.value});
        });
        this.tsChartData = series;
		//this.$.tschart.chartData = series;
		//this.$.tschart.set("chartData",series);
		if (chart != null)
		{
		chart.set('chartData',series);
		}
      },
	  // set time range for rangepicker
  _updateRangePicker: function(from, to) {
    var range = {
      from: new Date(from).toISOString(),
      to: new Date(to).toISOString(),
    };
    var $rangePicker = this.$.rangepicker;

    $rangePicker.range = range;

    //['from', 'to'].map(function(which) {
      //var picker = $rangePicker.querySelector('px-calendar-picker#' + which);
      //picker.blockDatesBefore = range.from;
      //picker.blockDatesAfter = range.to;
      //picker.baseDate = moment(range[which]);
    //});
  }
    });
  </script>
</dom-module>

**Comment by soccerchenjun** [comment]
chart has been pointed at px-vis-timeseries element, could you help me check my file
https://codepen.io/soccerchenjun/pen/MmvVJb

**Comment by nonmetalhail** [comment]
It is rather difficult to tell since you just cut and pasted code into the codepen and it isnt functional. You should go [here](https://www.predix-ui.com/#/components/px-vis-timeseries/) and use the pre-configured codepen to produce something functional. 

My guess is that your importHref isnt working; that would cause the component not to load and then polymer would not exist on that element. Alternatively, if you believe it is loaded, you can try just binding the data to the chart and using set on your winddata component to update it. 

You should also not be calling private functions on components. Private functions are denoted with the `_`, such as `this._updateRangePicker(rangeFrom, rangeTo);`. They are for internal use within the component and directly calling them may not yield the desired results and cause undefined behaviors within the component. For the rangepicker, there are public ways of updating it. 

I would also caution you against using the javascript date object. It is implemented differently across browsers and can yield different times in different browsers. I would use Moment.js instead.
