### ISSUE TITLE
Slowness in Rendering with Event Markers

### ISSUE THREAD

**Issue by jonkishkunasge** [PredixDev/px-vis-timeseries#51]
## Expected behavior and actual behavior:
Expected: Chart can render with ~1000 events markers in 2 seconds or less.
Actual: Chart rendering with ~1000 events markers incurs additional 40-45 seconds in Internet Explorer 11, additional 5-8 seconds in Chrome.

## Steps to reproduce the problem:
See examples feeding in ~1000 event markers at these codepens:
https://codepen.io/jkishkunasGE/pen/BRYyeN?editors=1001
https://codepen.io/jkishkunasGE/pen/zwRGae?editors=1001

Overhead time is more apparent/measurable when running locally with chart time series and event data set directly in the properties:
1. Setup and run the px-vis-timeseries codebase locally.
2. Modify the demo/index.html code to have the event config and event data used in the above codepens.
3. Measure the time taken with and without the event data/config to determine the overhead time for the event markers.
4. Vary the event markers between font awesome, custom images, and unicode, and observe that timings do not improve.
5. Vary the rendering to canvas and progressive rendering settings from true/false and observe that timings do not improve.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
Component: px-vis-timeseries v1.1.1, px-vis v1.1.9
Google Chrome v58 as well as Internet Explorer v11 (did not test other browsers)
OS: Windows 7, 64-bit
CPU: Intel Xeon CPU E5-1650v3 @3.5Ghz, 3.5Ghz
RAM: 32 GB

## Screenshots (_optional, but very helpful_):
Performance issue...see the codepens above.

## Code examples

See examples feeding in ~1000 event markers at these codepens:
https://codepen.io/jkishkunasGE/pen/BRYyeN?editors=1001
https://codepen.io/jkishkunasGE/pen/zwRGae?editors=1001

**Comment by benoitjchevalier** [comment]
I've been able to reproduce. I don't think we expected that many events being created, in this example we are paying the price of stamping 1000 px-vis-events (which themselves stamp one tooltip each, ouch).
One solution to investigate would be to have 1 px-vis-event handle all the events, having only 1 tooltip moving around and drawing everything itself. 

How critical is this improvement to you? The change would be non-trivial and might need to be prioritized against other features. 

We could temporarily limit the problem by adding a property to not create a tooltip, but that might defeat the purpose of the event... Also note for us to  remove the debounce in drawing which hurt perf

**Comment by jonkishkunasge** [comment]
This is a major issue for us, so your help would be greatly appreciated. My TPM is in touch via email on the priority. Internet Explorer is particularly problematic, taking minutes of time to render a few charts on screen. But even Chrome incurs some impact, as noted, and it is causing us to miss our target loading time for charts.

We would be good with having an option to eliminate tooltips from the event markers, we use different markers to denote different types of events, so the marker itself is sufficient for our use case. Would it be quick to try eliminating the tooltips and see what difference it makes, to gauge the impact? 

I'm not certain what you meant on the "debounce" option, could you explain?

I'm open to other ideas, too.

Thanks!

**Comment by benoitjchevalier** [comment]
I've added an `enableTooltip` option in eventConfig and made a minor tweak (the debounce thing, , this was just meant as a note for us when looking at this). If you set that to false the events should draw a bit more than twice as fast (which is still pretty slow for a lot of them...).

Anything more will require a rework of the events and will take some time, I understand that our TPMs are in contact regarding that.

available in px-vis 1.1.10

**Comment by benoitjchevalier** [comment]
ps: disabling the tooltip will solve the massive memory hog that the events are currently causing in the charts.

**Comment by jonkishkunasge** [comment]
Thanks for the quick turnaround. I see results like you mention in Chrome (twice as fast rendering), but not in Internet Explorer 11. Did you see any noticeable improvement in IE?

**Comment by jonkishkunasge** [comment]
Question - I no longer see any event marker tooltip in px-vis 1.1.10, with or without the added "enableTooltip" setting, and even with it set to true. I'll leave it set to false - but can you confirm whether event marker tooltips still show if it is set to true?

**Comment by benoitjchevalier** [comment]
I noticed the same thing yesterday, I have a fix ready, I'm going to bundle it with another change to events to allow formatting the timezone/timestamp in the tooltip of events. Release sometime today.

Regarding the perfs I ran a few tests yesterday on the new version with the upcoming fix and I did see a similar gain on IE:
drawing a timeseries with 4k points, 1k markers (in ms):

                  No markers         Markers with tooltip       Markers without tooltip
Chrome       289                             2245                                   1130
IE                 993                            32170                                14665

I don't expect the fix to have changed the performance, but you can pick up the new version once I've released it and try again

**Comment by benoitjchevalier** [comment]
The fix is available in px-vis 1.1.11

**Comment by jonkishkunasge** [comment]
Trying px-vis 1.1.11 and the tooltips are now always there. Can you confirm that the fix works in px-vis 1.1.11? If so, can you give a code snippet or codepen example so that I can ensure I am setting the setting correctly?

**Comment by benoitjchevalier** [comment]
How are you setting the eventConfig? The `enableTooltip` part has to be within a specific event type, e.g:
```

chart.eventConfig = {
          "fa":{
            "color": "blue",
            "icon": "fa-camera",
            "type": "fa",
            "offset":[0,0],
            "lineColor": "red",
            "lineWeight": this._chartOptions.eventsNoLine ? 0 : 1,
            'enableTooltip': this._chartOptions.eventsNoTooltip ? false : true
          },
          "unicode":{
            "color": "green",
            "icon": "\uf015",
            "type": "unicode",
            "offset":[1,0],
            "lineWeight": this._chartOptions.eventsNoLine ? 0 : 1,
            'enableTooltip': this._chartOptions.eventsNoTooltip ? false : true
          },
          "default":{
            "lineWeight": this._chartOptions.eventsNoLine ? 0 : 1,
            'enableTooltip': this._chartOptions.eventsNoTooltip ? false : true
          }
        };
```

I'm currently rebuilding demos but it's working locally

**Comment by jonkishkunasge** [comment]
Thanks! I was adding directly under eventConfig. It works when I add it per-event-type.

**Comment by benoitjchevalier** [comment]
v2.1.3 now includes a new `markerConfig` and `markerData` feature, allowing to draw a lot of markers above and below the chart. This feature uses canvas and can handle thousands of markers.
