### ISSUE TITLE
Negative Values/Scaling Issue

### ISSUE THREAD

**Issue by kjrdel** [PredixDev/px-vis-timeseries#53]
I recently upgraded from px-vis-timeseries 0.5.8 to the latest release, 1.1.1.  I've noticed that when plotting data with negative values, the timeseries doesn't scale correctly to include the part of the data which includes those negative values.  Also, there are times when the y-axis values actually decrease instead of increase.

As an example, here is a screenshot of some data with only negative values plotted using v0.5.8.  The zoom is the default zoom and has not been modified:

![capture](https://cloud.githubusercontent.com/assets/28785823/26212224/de44aae6-3bc2-11e7-90a4-f037a495414d.PNG)

And here is the same data plotted using v1.1.1:

![capture_2](https://cloud.githubusercontent.com/assets/28785823/26212354/4a1a0248-3bc3-11e7-811a-bce98410b3b0.PNG)

The y-axis doesn't scale correctly and none of the data is displayed.  The values on the y-axis are also decreasing instead of increasing.  If I manually pan up, I can find the data, but it is essentially plotted upside-down:

![capture_3](https://cloud.githubusercontent.com/assets/28785823/26213524/652f6768-3bc7-11e7-9ab2-ad88e48d864b.PNG)

Any insight into this issue is appreciated.

**Comment by nonmetalhail** [comment]
By default, the chart y-extents start at 0. You can specify that you want dynamic y-min extents by adding specifying dynamic extents:

```
<px-vis-timeseries
    chart-extents='{
        "x": ["dynamic","dynamic"],
        "y": ["dynamic","dynamic"]
    }'>
</px-vis-timeseries>
```

**Comment by kjrdel** [comment]
Thanks.  I guess the default ranges must have changed because I didn't have to explicitly set these before.  Either way, it seems to resolve the issue.
