### ISSUE TITLE
Issue selection tab(zoom, pan, tooltip)

### ISSUE THREAD

**Issue by Dhawal0693** [PredixDev/px-vis-timeseries#56]
Hi,

I have observed an issue wherein if a user clicks on zoom button and now user clicks anywhere outside the chart the zoom panel doesn't disappear. 
The panel only disappears when user clicks on other button. This is observed for each button available.

Is this the expected behaviour or this is an issue?

**Comment by benoitjchevalier** [comment]
Hello,

that is the expected behavior, the secondary toolbar is displayed relatively to which main button is selected. So as long as the main "zoom" button is selected the secondary toolbar for zooming will be displayed.
