### ISSUE TITLE
Is it possible to move to plotted data point of Px-vis-timeseries chart on key press ??

### ISSUE THREAD

**Issue by 502767168** [PredixDev/px-vis-timeseries#58]
Hi,

I have a requirement where I need to move on plotted data points of Px-vis-timeseries chart on left, right, up and down key press. Is this already implemented on Px-vis-timeseries? If not already implemented, need help to find solution for same.

**Comment by nonmetalhail** [comment]
Nope. But if you listen to the keys in your app, you can adjust the selectedDomain of the chart to move the chart accordingly.
