### ISSUE TITLE
Access to dummy data

### ISSUE THREAD

**Issue by udyandutta** [PredixDev/px-vis-timeseries#6]
Experimenting with the component, demo file needs "delta-egt-cruiseXY.json" , "delta-egt-cruise.json", "hpt-acc-position-cruise.json" and "delta-egt-cruise-events.json". It will help if someone can share these files. 

Also, an updated Readme will help quiet a bit. 
Also, random fyi, I had to make the following updates to 'demo.html' to get it to run.
'''
<link rel="import" href="/public/bower_components/px-theme/px-theme.html"/>
<link rel="import" href="px-vis-timeseries.html"/>
<link rel="import" href="/public/bower_components/px-vis/px-vis-data.html"/>
<link rel="import" href="/public/bower_components/px-rangepicker/px-rangepicker.html"/>
<link rel="import" href="/public/bower_components/px-vis/px-vis-data-converter.html"/>
'''

**Comment by benoitjchevalier** [comment]
Hello,

those files are part of "px-demo-data" which should be fetched when doing a bower install.

I would also recommend having a look at the [demo and API page](http://predixdev.github.io/predix-ui/?show=px-vis-timeseries&type=component ), they might be more useful than the Readme when trying to work with/explore a component

I think you forgot to paste the bit of code you had to change to make the demo work ;). 

Cheers,
Ben
