### ISSUE TITLE
"Render to Canvas" behaves unpredictable

### ISSUE THREAD

**Issue by 212324963** [PredixDev/px-vis-timeseries#60]
**Chrome:**
works fully, but takes a lot of time

**Safari:**
Navigator remains empty
![screen shot 2017-08-04 at 10 58 06 am](https://user-images.githubusercontent.com/25111262/28980739-d11bf9c2-7903-11e7-9a38-4cc02db2530d.png)

**Firefox:**
No data loads

![screen shot 2017-08-04 at 10 57 36 am](https://user-images.githubusercontent.com/25111262/28980711-bfb1b64a-7903-11e7-8a11-4035d9b5624e.png)

**Comment by nonmetalhail** [comment]
This appears to be an issue across all charts. Fix will be released with our zoom feature
