### ISSUE TITLE
How to get legend svg in px-vis-timeseries?

### ISSUE THREAD

**Issue by rickray21** [PredixDev/px-vis-timeseries#61]
At present, while using getCombinedImage() or getImage() function, then inside callback the encoded chart svg has come but the legend image which is shown just above the chart is not coming with the chart svg. How do I grab the legend svg also with that chart image.

**Comment by nonmetalhail** [comment]
`getCombinedImage: function(callback,  renderLegend)`

`getCombinedImage` takes two args, a callback function run on success and a bool specifying if you want to render the legend. Pass `true` in for the second arg and it should work.

**Comment by 502767168** [comment]
Thanks nonmetalhail.. It's very useful. Now the legend is coming properly.
