### ISSUE TITLE
Filling the chart dynamically

### ISSUE THREAD

**Issue by ffguven** [PredixDev/px-vis-timeseries#64]
Is there any solution in Predix UI to fill the chart dynamically without using home made javascript codes? I have looked for some solutions but couldn't find in Predix UI.

**Comment by benoitjchevalier** [comment]
Hello,

can you please clarify your question? Are you talking about "filling" the data (i.e providing data to the chart) or a visual fill under a series visual representation?

**Comment by ffguven** [comment]
I am talking about providing data to the chart. Say that i am ingesting data to Time Series for an asset and at that moment i want to update the chart with updated Time Series data real time without refreshing the page. I can solve the case by making jQuery AJAX calls to REST API but i am asking whether there is a solution for this case in Predix UI Components or not?

**Comment by gstroup** [comment]
You can see an example of this using web sockets, in the Predix Web App Starter:

https://github.com/PredixDev/predix-webapp-starter

There's not a Predix UI component to query your data source.  You can use Google's iron-ajax for AJAX calls.

**Comment by ffguven** [comment]
Thank you for your attention. I'm gonna look at the provided link and iron-ajax.
