### ISSUE TITLE
Titles are hardcoded when they should be passed in...

### ISSUE THREAD

**Issue by nonmetalhail** [PredixDev/px-vis-timeseries#7]

**Comment by KevinVecchione** [comment]
Agree. Time series data isn't always in Hz. At the moment this issue is forcing me to roll my own timeseries charts using px-vis components or using the deprecated px-chart.

**Comment by nonmetalhail** [comment]
@KevinVecchione This is now fixed in v0.2.x versions. Please give it a try and if you see other issues which are preventing you from adopting, it would help us a lot if you could log an issue. Sometimes, silly mistakes like this one just get overlooked

**Comment by KevinVecchione** [comment]
@nonmetalhail Thanks, looks good now, and I will log issues for future enhancement requests.
