### ISSUE TITLE
Not able to exit zoom mode

### ISSUE THREAD

**Issue by stephanepilla** [PredixDev/px-vis-timeseries#70]
Hello, 

when we zoom in on the graph and then reset the zoom, the mouse cursor stays in "zoom mode". 
One consequence is that the tooltip is not displayed anymore.

## Expected behavior:
When the zoom toolbar is collapsed, the graph should automatically exit the zoom mode.

## Environment : 
"px-vis": "4.2.2",
"px-vis-timeseries": "3.2.1",

## Screenshots:
![image](https://user-images.githubusercontent.com/17046306/33124880-d36fb5fc-cf7e-11e7-9505-cc0ae6a62a9a.png)

**Comment by benoitjchevalier** [comment]
This is the intended behavior. To go back to tooltip mode you'll have to click the tooltip mode in the toolbar.

However the toolbar is fully customizable so you could modify the behavior the achieve the functionality you're after by running a function when clicking the reset zoom button for example. More info here: https://www.predix-ui.com/#/develop/vis/configure-toolbar
