### ISSUE TITLE
Navigator handles can overlap in some instances

### ISSUE THREAD

**Issue by 212568333** [PredixDev/px-vis-timeseries#71]
# Submit an Issue
Note: Benoit Chevalier is already looking into the issue.

## Expected behavior and actual behavior:
Expected: When you drag and drop the East and West Navigator Bars on top of one another, data appears in chart normally.
Actual: When you drag and drop the East and West Navigator Bars on top of one another, data displays multiple lines when only 1 set of data exists. 

## Steps to reproduce the problem:
See video (around 0:53 mark)
https://ge.box.com/s/xas7x5etg1m0cxi60o6txgeiyodow39d

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
"px-vis-timeseries": "3.2.5", Chrome Version 61.0.3163.100, MacOS

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by benoitjchevalier** [comment]
steps to reproduce:
programatically set `selectedDomain` to same start and stop timestamp
handles can now overlap
keep trying to make them overlap, sometime the "multi line" drawing happens

we'll add more guards around preventing the handles from being on top of each other

**Comment by benoitjchevalier** [comment]
actually fixed in vis 4.5.0
