### ISSUE TITLE
Edit Striping updating stripeData attribute with Date object instead of Epoch

### ISSUE THREAD

**Issue by eligoldweber** [PredixDev/px-vis-timeseries#72]
# Submit an Issue
Hi,

When editing stripes (only resize and move, not delete or add) the chart attempts to store a Date object in the stripeData data structure. 

## Expected behavior and actual behavior:

Expected behavior: When editing a stripe. Once the action is done, that chart's stripeData attribute should reflect the updated stripes. A stripe is represented as a 2 element array with a start timestamp and an end timestamp in epoch time.

Actual behavior: When editing a strip. After the action is done the 2 element array with epoch times is gone from the chart's stripData, and there is an array with a Date object

## Steps to reproduce the problem:

1. Add a stripe, observe that chart's stripeData
2. Edit a stripe ( move it or resize ), observe the chart's stripeData 

## Screenshots
![image](https://user-images.githubusercontent.com/5432518/34846686-91689ade-f6de-11e7-938b-a15e5efb5a2c.png)
![image](https://user-images.githubusercontent.com/5432518/34846724-bc6a12da-f6de-11e7-9221-4698c973c437.png)

![image](https://user-images.githubusercontent.com/5432518/34846749-d325ff52-f6de-11e7-8121-a6817b268707.png)

![image](https://user-images.githubusercontent.com/5432518/34846869-2ff31706-f6df-11e7-8386-f7bae33a13cd.png)

Reproduction of issue on striping demo: https://www.predix-ui.com/px-vis-demos/px-vis-demos/striping.html
![image](https://user-images.githubusercontent.com/5432518/34845733-894f4576-f6db-11e7-99c7-a1e9bca9b722.png)

**Comment by nonmetalhail** [comment]
Thanks for the thorough write up. Fixed in v3.4.2
