### ISSUE TITLE
Unable to see X-Axis Title

### ISSUE THREAD

**Issue by udyandutta** [PredixDev/px-vis-timeseries#9]
Hey, 
I am unable to see the title for the Y axis. Will be attaching a screenshot for more info. Issue seen on  "version": "0.2.1".

PS : Awesome work with the the px-vis-timeseries component. Its very feature rich and useful for our timeseries streaming use case. 

<Screenshot>

![issue1](https://cloud.githubusercontent.com/assets/18316512/18220829/965be7ac-712a-11e6-97b0-d103c228adcc.png)

**Comment by randyaskin** [comment]
This refers to an old version of px-vis-timeseries, is this still an issue in later versions?
@nonmetalhail @benoitjchevalier

**Comment by benoitjchevalier** [comment]
I think the issue was that there was no control over the margin in timeseries, which should now be configurable in v1.0.0-alpha. However the latest production-ready version probably sill has the issue

**Comment by benoitjchevalier** [comment]
Fixed with 1.0.0 release
